/****************************************************************************
 *  Copyright (C) 2025 Xiaomi Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ***************************************************************************/

#ifndef CAN_MESSAGE_RAM_H
#define CAN_MESSAGE_RAM_H

#include "can_filter.h"

# define CONFIG_CAN0_NODE0_DED_TX_BUF_NUM 15
# define CONFIG_CAN0_NODE0_TX_FIFO_Q_NUM 17
# define CONFIG_CAN0_NODE1_DED_TX_BUF_NUM 0
# define CONFIG_CAN0_NODE1_TX_FIFO_Q_NUM 0
# define CONFIG_CAN0_NODE2_DED_TX_BUF_NUM 16
# define CONFIG_CAN0_NODE2_TX_FIFO_Q_NUM 16
# define CONFIG_CAN0_NODE3_DED_TX_BUF_NUM 0
# define CONFIG_CAN0_NODE3_TX_FIFO_Q_NUM 0
# define CONFIG_CAN1_NODE0_DED_TX_BUF_NUM 5
# define CONFIG_CAN1_NODE0_TX_FIFO_Q_NUM 27
# define CONFIG_CAN1_NODE1_DED_TX_BUF_NUM 0
# define CONFIG_CAN1_NODE1_TX_FIFO_Q_NUM 0
# define CONFIG_CAN1_NODE2_DED_TX_BUF_NUM 5
# define CONFIG_CAN1_NODE2_TX_FIFO_Q_NUM 27
# define CONFIG_CAN1_NODE3_DED_TX_BUF_NUM 0
# define CONFIG_CAN1_NODE3_TX_FIFO_Q_NUM 0
# define CONFIG_CAN2_NODE0_DED_TX_BUF_NUM 0
# define CONFIG_CAN2_NODE0_TX_FIFO_Q_NUM 0
# define CONFIG_CAN2_NODE1_DED_TX_BUF_NUM 0
# define CONFIG_CAN2_NODE1_TX_FIFO_Q_NUM 0
# define CONFIG_CAN2_NODE2_DED_TX_BUF_NUM 0
# define CONFIG_CAN2_NODE2_TX_FIFO_Q_NUM 0
# define CONFIG_CAN2_NODE3_DED_TX_BUF_NUM 0
# define CONFIG_CAN2_NODE3_TX_FIFO_Q_NUM 0
# define CONFIG_CAN3_NODE0_DED_TX_BUF_NUM 0
# define CONFIG_CAN3_NODE0_TX_FIFO_Q_NUM 0
# define CONFIG_CAN3_NODE1_DED_TX_BUF_NUM 0
# define CONFIG_CAN3_NODE1_TX_FIFO_Q_NUM 0
# define CONFIG_CAN3_NODE2_DED_TX_BUF_NUM 0
# define CONFIG_CAN3_NODE2_TX_FIFO_Q_NUM 0
# define CONFIG_CAN3_NODE3_DED_TX_BUF_NUM 0
# define CONFIG_CAN3_NODE3_TX_FIFO_Q_NUM 0
# define CONFIG_CAN4_NODE0_DED_TX_BUF_NUM 0
# define CONFIG_CAN4_NODE0_TX_FIFO_Q_NUM 0
# define CONFIG_CAN4_NODE1_DED_TX_BUF_NUM 0
# define CONFIG_CAN4_NODE1_TX_FIFO_Q_NUM 0
# define CONFIG_CAN4_NODE2_DED_TX_BUF_NUM 0
# define CONFIG_CAN4_NODE2_TX_FIFO_Q_NUM 0
# define CONFIG_CAN4_NODE3_DED_TX_BUF_NUM 0
# define CONFIG_CAN4_NODE3_TX_FIFO_Q_NUM 0

#define CONFIG_CAN0_NODE0_TEF_NUM 0
#define CONFIG_CAN0_NODE0_STD_RT_NUM (CAN0_NODE0_UNICAST_ROUTER_NUM + CAN0_NODE0_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN0_NODE0_STD_FRT_NUM 0
#define CONFIG_CAN0_NODE0_STD_TSD_NUM 0

#define CONFIG_CAN0_NODE1_TEF_NUM 0
#define CONFIG_CAN0_NODE1_STD_RT_NUM (CAN0_NODE1_UNICAST_ROUTER_NUM + CAN0_NODE1_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN0_NODE1_STD_FRT_NUM 0
#define CONFIG_CAN0_NODE1_STD_TSD_NUM 0

#define CONFIG_CAN0_NODE2_TEF_NUM 0
#define CONFIG_CAN0_NODE2_STD_RT_NUM (CAN0_NODE2_UNICAST_ROUTER_NUM + CAN0_NODE2_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN0_NODE2_STD_FRT_NUM 0
#define CONFIG_CAN0_NODE2_STD_TSD_NUM 0

#define CONFIG_CAN0_NODE3_TEF_NUM 0
#define CONFIG_CAN0_NODE3_STD_RT_NUM (CAN0_NODE3_UNICAST_ROUTER_NUM + CAN0_NODE3_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN0_NODE3_STD_FRT_NUM 0
#define CONFIG_CAN0_NODE3_STD_TSD_NUM 0

#define CONFIG_CAN1_NODE0_TEF_NUM 0
#define CONFIG_CAN1_NODE0_STD_RT_NUM (CAN1_NODE0_UNICAST_ROUTER_NUM + CAN1_NODE0_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN1_NODE0_STD_FRT_NUM 0
#define CONFIG_CAN1_NODE0_STD_TSD_NUM 0

#define CONFIG_CAN1_NODE1_TEF_NUM 0
#define CONFIG_CAN1_NODE1_STD_RT_NUM (CAN1_NODE1_UNICAST_ROUTER_NUM + CAN1_NODE1_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN1_NODE1_STD_FRT_NUM 0
#define CONFIG_CAN1_NODE1_STD_TSD_NUM 0

#define CONFIG_CAN1_NODE2_TEF_NUM 0
#define CONFIG_CAN1_NODE2_STD_RT_NUM (CAN1_NODE2_UNICAST_ROUTER_NUM + CAN1_NODE2_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN1_NODE2_STD_FRT_NUM 0
#define CONFIG_CAN1_NODE2_STD_TSD_NUM 0

#define CONFIG_CAN1_NODE3_TEF_NUM 0
#define CONFIG_CAN1_NODE3_STD_RT_NUM (CAN1_NODE3_UNICAST_ROUTER_NUM + CAN1_NODE3_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN1_NODE3_STD_FRT_NUM 0
#define CONFIG_CAN1_NODE3_STD_TSD_NUM 0

#define CONFIG_CAN2_NODE0_TEF_NUM 0
#define CONFIG_CAN2_NODE0_STD_RT_NUM (CAN2_NODE0_UNICAST_ROUTER_NUM + CAN2_NODE0_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN2_NODE0_STD_FRT_NUM 0
#define CONFIG_CAN2_NODE0_STD_TSD_NUM 0

#define CONFIG_CAN2_NODE1_TEF_NUM 0
#define CONFIG_CAN2_NODE1_STD_RT_NUM (CAN2_NODE1_UNICAST_ROUTER_NUM + CAN2_NODE1_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN2_NODE1_STD_FRT_NUM 0
#define CONFIG_CAN2_NODE1_STD_TSD_NUM 0

#define CONFIG_CAN2_NODE2_TEF_NUM 0
#define CONFIG_CAN2_NODE2_STD_RT_NUM (CAN2_NODE2_UNICAST_ROUTER_NUM + CAN2_NODE2_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN2_NODE2_STD_FRT_NUM 0
#define CONFIG_CAN2_NODE2_STD_TSD_NUM 0

#define CONFIG_CAN2_NODE3_TEF_NUM 0
#define CONFIG_CAN2_NODE3_STD_RT_NUM (CAN2_NODE3_UNICAST_ROUTER_NUM + CAN2_NODE3_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN2_NODE3_STD_FRT_NUM 0
#define CONFIG_CAN2_NODE3_STD_TSD_NUM 0

#define CONFIG_CAN3_NODE0_TEF_NUM 0
#define CONFIG_CAN3_NODE0_STD_RT_NUM (CAN3_NODE0_UNICAST_ROUTER_NUM + CAN3_NODE0_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN3_NODE0_STD_FRT_NUM 0
#define CONFIG_CAN3_NODE0_STD_TSD_NUM 0

#define CONFIG_CAN3_NODE1_TEF_NUM 0
#define CONFIG_CAN3_NODE1_STD_RT_NUM (CAN3_NODE1_UNICAST_ROUTER_NUM + CAN3_NODE1_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN3_NODE1_STD_FRT_NUM 0
#define CONFIG_CAN3_NODE1_STD_TSD_NUM 0

#define CONFIG_CAN3_NODE2_TEF_NUM 0
#define CONFIG_CAN3_NODE2_STD_RT_NUM (CAN3_NODE2_UNICAST_ROUTER_NUM + CAN3_NODE2_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN3_NODE2_STD_FRT_NUM 0
#define CONFIG_CAN3_NODE2_STD_TSD_NUM 0

#define CONFIG_CAN3_NODE3_TEF_NUM 0
#define CONFIG_CAN3_NODE3_STD_RT_NUM (CAN3_NODE3_UNICAST_ROUTER_NUM + CAN3_NODE3_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN3_NODE3_STD_FRT_NUM 0
#define CONFIG_CAN3_NODE3_STD_TSD_NUM 0

#define CONFIG_CAN4_NODE0_TEF_NUM 0
#define CONFIG_CAN4_NODE0_STD_RT_NUM (CAN4_NODE0_UNICAST_ROUTER_NUM + CAN4_NODE0_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN4_NODE0_STD_FRT_NUM 0
#define CONFIG_CAN4_NODE0_STD_TSD_NUM 0

#define CONFIG_CAN4_NODE1_TEF_NUM 0
#define CONFIG_CAN4_NODE1_STD_RT_NUM (CAN4_NODE1_UNICAST_ROUTER_NUM + CAN4_NODE1_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN4_NODE1_STD_FRT_NUM 0
#define CONFIG_CAN4_NODE1_STD_TSD_NUM 0

#define CONFIG_CAN4_NODE2_TEF_NUM 0
#define CONFIG_CAN4_NODE2_STD_RT_NUM (CAN4_NODE2_UNICAST_ROUTER_NUM + CAN4_NODE2_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN4_NODE2_STD_FRT_NUM 0
#define CONFIG_CAN4_NODE2_STD_TSD_NUM 0

#define CONFIG_CAN4_NODE3_TEF_NUM 0
#define CONFIG_CAN4_NODE3_STD_RT_NUM (CAN4_NODE3_UNICAST_ROUTER_NUM + CAN4_NODE3_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN4_NODE3_STD_FRT_NUM 0
#define CONFIG_CAN4_NODE3_STD_TSD_NUM 0

#endif
