/****************************************************************************
 *  Copyright (C) 2025 Xiaomi Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ***************************************************************************/

#ifndef __VENDOR_CAN_MRAM_TC3_H
#define __VENDOR_CAN_MRAM_TC3_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#ifdef CONFIG_AURIX_MCMCAN
#ifdef CONFIG_AURIX_MCMCAN_MERAM_CONFIG

/* #include "can_message_ram.h" */

#include "can_filter.h"

#endif

/* cre_cfg.h */
#define CAN0_NODE0_MUL_ROUTING NULL
#define CAN0_NODE1_MUL_ROUTING NULL
#define CAN0_NODE2_MUL_ROUTING NULL
#define CAN0_NODE3_MUL_ROUTING NULL
#define CAN1_NODE0_MUL_ROUTING NULL
#define CAN1_NODE2_MUL_ROUTING NULL
#define CAN2_NODE0_MUL_ROUTING NULL
#define CAN2_NODE1_MUL_ROUTING NULL

#define CAN2_NODE2_UNICAST_ROUTER_NUM 0
#define CAN1_NODE1_UNICAST_ROUTER_NUM 0
#define CAN2_NODE3_UNICAST_ROUTER_NUM 0
#define CAN1_NODE3_UNICAST_ROUTER_NUM 0
#define CAN1_NODE0_UNICAST_ROUTER_NUM 0
#define CAN0_NODE1_UNICAST_ROUTER_NUM 0
#define CAN0_NODE0_UNICAST_ROUTER_NUM 0
#define CAN0_NODE2_UNICAST_ROUTER_NUM 0
#define CAN0_NODE3_UNICAST_ROUTER_NUM 0
#define CAN1_NODE2_UNICAST_ROUTER_NUM 0
#define CAN2_NODE0_UNICAST_ROUTER_NUM 0
#define CAN2_NODE1_UNICAST_ROUTER_NUM 0
#define CAN2_NODE2_MULTICAST_ROUTER_NUM 0
#define CAN1_NODE1_MULTICAST_ROUTER_NUM 0
#define CAN2_NODE3_MULTICAST_ROUTER_NUM 0
#define CAN1_NODE3_MULTICAST_ROUTER_NUM 0
#define CAN1_NODE0_MULTICAST_ROUTER_NUM 0
#define CAN0_NODE1_MULTICAST_ROUTER_NUM 0
#define CAN0_NODE0_MULTICAST_ROUTER_NUM 0
#define CAN0_NODE2_MULTICAST_ROUTER_NUM 0
#define CAN0_NODE3_MULTICAST_ROUTER_NUM 0
#define CAN1_NODE2_MULTICAST_ROUTER_NUM 0
#define CAN2_NODE0_MULTICAST_ROUTER_NUM 0
#define CAN2_NODE1_MULTICAST_ROUTER_NUM 0

/* can_message_ram.h */
#define CONFIG_CAN0_NODE0_DED_TX_BUF_NUM 5
#define CONFIG_CAN0_NODE0_TX_FIFO_Q_NUM 5
#define CONFIG_CAN0_NODE1_DED_TX_BUF_NUM 5
#define CONFIG_CAN0_NODE1_TX_FIFO_Q_NUM 5
#define CONFIG_CAN0_NODE2_DED_TX_BUF_NUM 5
#define CONFIG_CAN0_NODE2_TX_FIFO_Q_NUM 5
#define CONFIG_CAN0_NODE3_DED_TX_BUF_NUM 5
#define CONFIG_CAN0_NODE3_TX_FIFO_Q_NUM 5
#define CONFIG_CAN1_NODE0_DED_TX_BUF_NUM 5
#define CONFIG_CAN1_NODE0_TX_FIFO_Q_NUM 5
#define CONFIG_CAN1_NODE1_DED_TX_BUF_NUM 5
#define CONFIG_CAN1_NODE1_TX_FIFO_Q_NUM 5
#define CONFIG_CAN1_NODE2_DED_TX_BUF_NUM 5
#define CONFIG_CAN1_NODE2_TX_FIFO_Q_NUM 5
#define CONFIG_CAN1_NODE3_DED_TX_BUF_NUM 5
#define CONFIG_CAN1_NODE3_TX_FIFO_Q_NUM 5
#define CONFIG_CAN2_NODE0_DED_TX_BUF_NUM 5
#define CONFIG_CAN2_NODE0_TX_FIFO_Q_NUM 5
#define CONFIG_CAN2_NODE1_DED_TX_BUF_NUM 5
#define CONFIG_CAN2_NODE1_TX_FIFO_Q_NUM 5
#define CONFIG_CAN2_NODE2_DED_TX_BUF_NUM 5
#define CONFIG_CAN2_NODE2_TX_FIFO_Q_NUM 5
#define CONFIG_CAN2_NODE3_DED_TX_BUF_NUM 5
#define CONFIG_CAN2_NODE3_TX_FIFO_Q_NUM 5

#define CONFIG_CAN0_NODE0_TEF_NUM 5
#define CONFIG_CAN0_NODE0_STD_RT_NUM (CAN0_NODE0_UNICAST_ROUTER_NUM + CAN0_NODE0_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN0_NODE0_STD_FRT_NUM (CAN0_NODE0_UNICAST_ROUTER_NUM + CAN0_NODE0_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN0_NODE0_STD_TSD_NUM (CAN0_NODE0_UNICAST_ROUTER_NUM + CAN0_NODE0_MULTICAST_ROUTER_NUM)

#define CONFIG_CAN0_NODE1_TEF_NUM 5
#define CONFIG_CAN0_NODE1_STD_RT_NUM (CAN0_NODE1_UNICAST_ROUTER_NUM + CAN0_NODE1_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN0_NODE1_STD_FRT_NUM (CAN0_NODE1_UNICAST_ROUTER_NUM + CAN0_NODE1_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN0_NODE1_STD_TSD_NUM (CAN0_NODE1_UNICAST_ROUTER_NUM + CAN0_NODE1_MULTICAST_ROUTER_NUM)

#define CONFIG_CAN0_NODE2_TEF_NUM 5
#define CONFIG_CAN0_NODE2_STD_RT_NUM (CAN0_NODE2_UNICAST_ROUTER_NUM + CAN0_NODE2_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN0_NODE2_STD_FRT_NUM (CAN0_NODE2_UNICAST_ROUTER_NUM + CAN0_NODE2_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN0_NODE2_STD_TSD_NUM (CAN0_NODE2_UNICAST_ROUTER_NUM + CAN0_NODE2_MULTICAST_ROUTER_NUM)

#define CONFIG_CAN0_NODE3_TEF_NUM 5
#define CONFIG_CAN0_NODE3_STD_RT_NUM (CAN0_NODE3_UNICAST_ROUTER_NUM + CAN0_NODE3_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN0_NODE3_STD_FRT_NUM (CAN0_NODE3_UNICAST_ROUTER_NUM + CAN0_NODE3_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN0_NODE3_STD_TSD_NUM (CAN0_NODE3_UNICAST_ROUTER_NUM + CAN0_NODE3_MULTICAST_ROUTER_NUM)

#define CONFIG_CAN1_NODE0_TEF_NUM 5
#define CONFIG_CAN1_NODE0_STD_RT_NUM (CAN1_NODE0_UNICAST_ROUTER_NUM + CAN1_NODE0_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN1_NODE0_STD_FRT_NUM (CAN1_NODE0_UNICAST_ROUTER_NUM + CAN1_NODE0_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN1_NODE0_STD_TSD_NUM (CAN1_NODE0_UNICAST_ROUTER_NUM + CAN1_NODE0_MULTICAST_ROUTER_NUM)

#define CONFIG_CAN1_NODE1_TEF_NUM 5
#define CONFIG_CAN1_NODE1_STD_RT_NUM (CAN1_NODE1_UNICAST_ROUTER_NUM + CAN1_NODE1_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN1_NODE1_STD_FRT_NUM (CAN1_NODE1_UNICAST_ROUTER_NUM + CAN1_NODE1_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN1_NODE1_STD_TSD_NUM (CAN1_NODE1_UNICAST_ROUTER_NUM + CAN1_NODE1_MULTICAST_ROUTER_NUM)

#define CONFIG_CAN1_NODE2_TEF_NUM 5
#define CONFIG_CAN1_NODE2_STD_RT_NUM (CAN1_NODE2_UNICAST_ROUTER_NUM + CAN1_NODE2_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN1_NODE2_STD_FRT_NUM (CAN1_NODE2_UNICAST_ROUTER_NUM + CAN1_NODE2_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN1_NODE2_STD_TSD_NUM (CAN1_NODE2_UNICAST_ROUTER_NUM + CAN1_NODE2_MULTICAST_ROUTER_NUM)

#define CONFIG_CAN1_NODE3_TEF_NUM 5
#define CONFIG_CAN1_NODE3_STD_RT_NUM (CAN1_NODE3_UNICAST_ROUTER_NUM + CAN1_NODE3_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN1_NODE3_STD_FRT_NUM (CAN1_NODE3_UNICAST_ROUTER_NUM + CAN1_NODE3_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN1_NODE3_STD_TSD_NUM (CAN1_NODE3_UNICAST_ROUTER_NUM + CAN1_NODE3_MULTICAST_ROUTER_NUM)

#define CONFIG_CAN2_NODE0_TEF_NUM 5
#define CONFIG_CAN2_NODE0_STD_RT_NUM (CAN2_NODE0_UNICAST_ROUTER_NUM + CAN2_NODE0_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN2_NODE0_STD_FRT_NUM (CAN2_NODE0_UNICAST_ROUTER_NUM + CAN2_NODE0_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN2_NODE0_STD_TSD_NUM (CAN2_NODE0_UNICAST_ROUTER_NUM + CAN2_NODE0_MULTICAST_ROUTER_NUM)

#define CONFIG_CAN2_NODE1_TEF_NUM 5
#define CONFIG_CAN2_NODE1_STD_RT_NUM (CAN2_NODE1_UNICAST_ROUTER_NUM + CAN2_NODE1_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN2_NODE1_STD_FRT_NUM (CAN2_NODE1_UNICAST_ROUTER_NUM + CAN2_NODE1_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN2_NODE1_STD_TSD_NUM (CAN2_NODE1_UNICAST_ROUTER_NUM + CAN2_NODE1_MULTICAST_ROUTER_NUM)

#define CONFIG_CAN2_NODE2_TEF_NUM 5
#define CONFIG_CAN2_NODE2_STD_RT_NUM (CAN2_NODE2_UNICAST_ROUTER_NUM + CAN2_NODE2_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN2_NODE2_STD_FRT_NUM (CAN2_NODE2_UNICAST_ROUTER_NUM + CAN2_NODE2_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN2_NODE2_STD_TSD_NUM (CAN2_NODE2_UNICAST_ROUTER_NUM + CAN2_NODE2_MULTICAST_ROUTER_NUM)

#define CONFIG_CAN2_NODE3_TEF_NUM 5
#define CONFIG_CAN2_NODE3_STD_RT_NUM (CAN2_NODE3_UNICAST_ROUTER_NUM + CAN2_NODE3_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN2_NODE3_STD_FRT_NUM (CAN2_NODE3_UNICAST_ROUTER_NUM + CAN2_NODE3_MULTICAST_ROUTER_NUM)
#define CONFIG_CAN2_NODE3_STD_TSD_NUM (CAN2_NODE3_UNICAST_ROUTER_NUM + CAN2_NODE3_MULTICAST_ROUTER_NUM)

extern const volatile void * IfxCan_ramAddress[3];

/* can_mram_tc3.h */

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Miscellaneous macros to calculate the CAN Message RAM partition */

/* the uint is 1 byte. example: SID_FILTER_SIZE (4) indicate 4 bytes */

#define SID_FILTER_SIZE (4)
#define XID_FILTER_SIZE (8)
#define TXEVENT_SIZE (8)
#define R0_R1_SIZE (8)
#define T0_T1_SIZE (8)

/* this region size is fixed 96 words when CRE is enable, it include
 * some CRE Configuration and RX Host Buffer 0/1, TX Host Buffer 0/1.
 */

#define CRE_FIXED_SIZE (96 * 4)
#define CRE_STD_RT_ELEMENT_SIZE (4)
#define CRE_STD_FRT_ELEMENT_SIZE (4)
#define CRE_STD_TSD_ELEMENT_SIZE (4)
#define CRE_STD_TSD_ELEMENT_SIZE (4)

/* 16 bytes alignment */

#define CRE_SA_ALIGN(n) ((n + 15) & ~0xf)
#define CANMSG_DATAFILED_SIZE 64

/* Setup fixed Partition (5K bytes <-> NODEX Region Size)
 * NODE0: 0x0 ~ 0x1400
 * NODE1: 0x1400 ~ 0x2800
 * NODE2: 0x2800 ~ 0x3C00
 * NODE3: 0x3C00 ~ 0x5000
 *
 * Max Std filter NUM: 32
 * Total Rx Buffers(Rx Buffer, Rx Fifo0 and Rx Fifo1) number: 32
 * Max Tx Event FIFO number：16
 * total TX buffer Number：16
 * Max CRE region size：285 words
 * Total：4852 bytes.
 */

/* CAN0 Message RAM Region */

/* Where the XXX_NUM is in
 * CONFIG_CAN*_NODE*_SFL_NUM is in can_filter.h
 * CONFIG_CAN*_NODE*_RF0_NUM is in can_filter.h
 * CONFIG_CAN*_NODE*_RF1_NUM is in can_filter.h
 * CONFIG_CAN*_NODE*_RXBUF_NUM is in can_filter.h
 * CONFIG_CAN*_NODE*_TEF_NUM is in can_message_ram.h
 * CONFIG_CAN*_NODE*_DED_TX_BUF_NUM is in can_message_ram.h
 * CONFIG_CAN*_NODE*_TX_FIFO_Q_NUM is in can_message_ram.h
 * CONFIG_CAN*_NODE*_STD_RT_NUM is in can_message_ram.h
 * CONFIG_CAN*_NODE*_STD_FRT_NUM is in can_message_ram.h
 * CONFIG_CAN*_NODE*_STD_TSD_NUM is in can_message_ram.h
 */

/* CONFIG_AURIX_MCMCAN0 */
#define CAN0_NODE0_MRAM_SA 0x0
#define CAN0_NODE0_FLSSA CAN0_NODE0_MRAM_SA
#define CAN0_NODE0_F0SA (CAN0_NODE0_FLSSA + (CONFIG_CAN0_NODE0_SFL_NUM * SID_FILTER_SIZE))
#define CAN0_NODE0_F1SA (CAN0_NODE0_F0SA + (CONFIG_CAN0_NODE0_RF0_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN0_NODE0_RX_BUFSA (CAN0_NODE0_F1SA + (CONFIG_CAN0_NODE0_RF1_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN0_NODE0_EFSA (CAN0_NODE0_RX_BUFSA + (CONFIG_CAN0_NODE0_RXBUF_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN0_NODE0_TX_BUFSA (CAN0_NODE0_EFSA + (CONFIG_CAN0_NODE0_TEF_NUM * TXEVENT_SIZE))
#if defined(MCMCAN0_CRE_ENABLE)
#define CAN0_NODE0_CRE_SA CRE_SA_ALIGN(CAN0_NODE0_TX_BUFSA + ((CONFIG_CAN0_NODE0_DED_TX_BUF_NUM + CONFIG_CAN0_NODE0_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN0_NODE0_CRE_STD_RT_SA (CAN0_NODE0_CRE_SA + CRE_FIXED_SIZE)
#else
#define CAN0_NODE0_CRE_SA CAN0_NODE0_TX_BUFSA + ((CONFIG_CAN0_NODE0_DED_TX_BUF_NUM + CONFIG_CAN0_NODE0_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE))
#define CAN0_NODE0_CRE_STD_RT_SA CAN0_NODE0_CRE_SA
#endif
#define CAN0_NODE0_CRE_STD_FRT_SA (CAN0_NODE0_CRE_STD_RT_SA + (CONFIG_CAN0_NODE0_STD_RT_NUM * CRE_STD_RT_ELEMENT_SIZE))
#define CAN0_NODE0_CRE_STD_TSD_SA (CAN0_NODE0_CRE_STD_FRT_SA + (CONFIG_CAN0_NODE0_STD_FRT_NUM * CRE_STD_FRT_ELEMENT_SIZE))

/* CONFIG_AURIX_MCMCAN1 */
#define CAN0_NODE1_MRAM_SA (CAN0_NODE0_CRE_STD_TSD_SA + (CONFIG_CAN0_NODE0_STD_TSD_NUM * CRE_STD_TSD_ELEMENT_SIZE))
#define CAN0_NODE1_FLSSA CAN0_NODE1_MRAM_SA
#define CAN0_NODE1_F0SA (CAN0_NODE1_FLSSA + (CONFIG_CAN0_NODE1_SFL_NUM * SID_FILTER_SIZE))
#define CAN0_NODE1_F1SA (CAN0_NODE1_F0SA + (CONFIG_CAN0_NODE1_RF0_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN0_NODE1_RX_BUFSA (CAN0_NODE1_F1SA + (CONFIG_CAN0_NODE1_RF1_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN0_NODE1_EFSA (CAN0_NODE1_RX_BUFSA + (CONFIG_CAN0_NODE1_RXBUF_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN0_NODE1_TX_BUFSA (CAN0_NODE1_EFSA + (CONFIG_CAN0_NODE1_TEF_NUM * TXEVENT_SIZE))
#if defined(MCMCAN1_CRE_ENABLE)
#define CAN0_NODE1_CRE_SA CRE_SA_ALIGN(CAN0_NODE1_TX_BUFSA + ((CONFIG_CAN0_NODE1_DED_TX_BUF_NUM + CONFIG_CAN0_NODE1_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN0_NODE1_CRE_STD_RT_SA (CAN0_NODE1_CRE_SA + CRE_FIXED_SIZE)
#else
#define CAN0_NODE1_CRE_SA CAN0_NODE1_TX_BUFSA + ((CONFIG_CAN0_NODE1_DED_TX_BUF_NUM + CONFIG_CAN0_NODE1_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE))
#define CAN0_NODE1_CRE_STD_RT_SA CAN0_NODE1_CRE_SA
#endif
#define CAN0_NODE1_CRE_STD_FRT_SA (CAN0_NODE1_CRE_STD_RT_SA + (CONFIG_CAN0_NODE1_STD_RT_NUM * CRE_STD_RT_ELEMENT_SIZE))
#define CAN0_NODE1_CRE_STD_TSD_SA (CAN0_NODE1_CRE_STD_FRT_SA + (CONFIG_CAN0_NODE1_STD_FRT_NUM * CRE_STD_FRT_ELEMENT_SIZE))

/* CONFIG_AURIX_MCMCAN2 */
#define CAN0_NODE2_MRAM_SA (CAN0_NODE1_CRE_STD_TSD_SA + (CONFIG_CAN0_NODE1_STD_TSD_NUM * CRE_STD_TSD_ELEMENT_SIZE))
#define CAN0_NODE2_FLSSA CAN0_NODE2_MRAM_SA
#define CAN0_NODE2_F0SA (CAN0_NODE2_FLSSA + (CONFIG_CAN0_NODE2_SFL_NUM * SID_FILTER_SIZE))
#define CAN0_NODE2_F1SA (CAN0_NODE2_F0SA + (CONFIG_CAN0_NODE2_RF0_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN0_NODE2_RX_BUFSA (CAN0_NODE2_F1SA + (CONFIG_CAN0_NODE2_RF1_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN0_NODE2_EFSA (CAN0_NODE2_RX_BUFSA + (CONFIG_CAN0_NODE2_RXBUF_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN0_NODE2_TX_BUFSA (CAN0_NODE2_EFSA + (CONFIG_CAN0_NODE2_TEF_NUM * TXEVENT_SIZE))
#if defined(MCMCAN2_CRE_ENABLE)
#define CAN0_NODE2_CRE_SA CRE_SA_ALIGN(CAN0_NODE2_TX_BUFSA + ((CONFIG_CAN0_NODE2_DED_TX_BUF_NUM + CONFIG_CAN0_NODE2_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN0_NODE2_CRE_STD_RT_SA (CAN0_NODE2_CRE_SA + CRE_FIXED_SIZE)
#else
#define CAN0_NODE2_CRE_SA CAN0_NODE2_TX_BUFSA + ((CONFIG_CAN0_NODE2_DED_TX_BUF_NUM + CONFIG_CAN0_NODE2_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE))
#define CAN0_NODE2_CRE_STD_RT_SA CAN0_NODE2_CRE_SA
#endif
#define CAN0_NODE2_CRE_STD_FRT_SA (CAN0_NODE2_CRE_STD_RT_SA + (CONFIG_CAN0_NODE2_STD_RT_NUM * CRE_STD_RT_ELEMENT_SIZE))
#define CAN0_NODE2_CRE_STD_TSD_SA (CAN0_NODE2_CRE_STD_FRT_SA + (CONFIG_CAN0_NODE2_STD_FRT_NUM * CRE_STD_FRT_ELEMENT_SIZE))

/* CONFIG_AURIX_MCMCAN3 */
#define CAN0_NODE3_MRAM_SA (CAN0_NODE2_CRE_STD_TSD_SA + (CONFIG_CAN0_NODE2_STD_TSD_NUM * CRE_STD_TSD_ELEMENT_SIZE))
#define CAN0_NODE3_FLSSA CAN0_NODE3_MRAM_SA
#define CAN0_NODE3_F0SA (CAN0_NODE3_FLSSA + (CONFIG_CAN0_NODE3_SFL_NUM * SID_FILTER_SIZE))
#define CAN0_NODE3_F1SA (CAN0_NODE3_F0SA + (CONFIG_CAN0_NODE3_RF0_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN0_NODE3_RX_BUFSA (CAN0_NODE3_F1SA + (CONFIG_CAN0_NODE3_RF1_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN0_NODE3_EFSA (CAN0_NODE3_RX_BUFSA + (CONFIG_CAN0_NODE3_RXBUF_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN0_NODE3_TX_BUFSA (CAN0_NODE3_EFSA + (CONFIG_CAN0_NODE3_TEF_NUM * TXEVENT_SIZE))
#if defined(MCMCAN3_CRE_ENABLE)
#define CAN0_NODE3_CRE_SA CRE_SA_ALIGN(CAN0_NODE3_TX_BUFSA + ((CONFIG_CAN0_NODE3_DED_TX_BUF_NUM + CONFIG_CAN0_NODE3_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN0_NODE3_CRE_STD_RT_SA (CAN0_NODE3_CRE_SA + CRE_FIXED_SIZE)
#else
#define CAN0_NODE3_CRE_SA CAN0_NODE3_TX_BUFSA + ((CONFIG_CAN0_NODE3_DED_TX_BUF_NUM + CONFIG_CAN0_NODE3_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE))
#define CAN0_NODE3_CRE_STD_RT_SA CAN0_NODE3_CRE_SA
#endif
#define CAN0_NODE3_CRE_STD_FRT_SA (CAN0_NODE3_CRE_STD_RT_SA + (CONFIG_CAN0_NODE3_STD_RT_NUM * CRE_STD_RT_ELEMENT_SIZE))
#define CAN0_NODE3_CRE_STD_TSD_SA (CAN0_NODE3_CRE_STD_FRT_SA + (CONFIG_CAN0_NODE3_STD_FRT_NUM * CRE_STD_FRT_ELEMENT_SIZE))

/* CAN1 Message RAM Region */

/* CONFIG_AURIX_MCMCAN4 */
#define CAN1_NODE0_MRAM_SA 0x0
#define CAN1_NODE0_FLSSA CAN1_NODE0_MRAM_SA
#define CAN1_NODE0_F0SA (CAN1_NODE0_FLSSA + (CONFIG_CAN1_NODE0_SFL_NUM * SID_FILTER_SIZE))
#define CAN1_NODE0_F1SA (CAN1_NODE0_F0SA + (CONFIG_CAN1_NODE0_RF0_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN1_NODE0_RX_BUFSA (CAN1_NODE0_F1SA + (CONFIG_CAN1_NODE0_RF1_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN1_NODE0_EFSA (CAN1_NODE0_RX_BUFSA + (CONFIG_CAN1_NODE0_RXBUF_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN1_NODE0_TX_BUFSA (CAN1_NODE0_EFSA + (CONFIG_CAN1_NODE0_TEF_NUM * TXEVENT_SIZE))
#if defined(MCMCAN4_CRE_ENABLE)
#define CAN1_NODE0_CRE_SA CRE_SA_ALIGN(CAN1_NODE0_TX_BUFSA + ((CONFIG_CAN1_NODE0_DED_TX_BUF_NUM + CONFIG_CAN1_NODE0_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN1_NODE0_CRE_STD_RT_SA (CAN1_NODE0_CRE_SA + CRE_FIXED_SIZE)
#else
#define CAN1_NODE0_CRE_SA CAN1_NODE0_TX_BUFSA + ((CONFIG_CAN1_NODE0_DED_TX_BUF_NUM + CONFIG_CAN1_NODE0_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE))
#define CAN1_NODE0_CRE_STD_RT_SA CAN1_NODE0_CRE_SA
#endif
#define CAN1_NODE0_CRE_STD_FRT_SA (CAN1_NODE0_CRE_STD_RT_SA + (CONFIG_CAN1_NODE0_STD_RT_NUM * CRE_STD_RT_ELEMENT_SIZE))
#define CAN1_NODE0_CRE_STD_TSD_SA (CAN1_NODE0_CRE_STD_FRT_SA + (CONFIG_CAN1_NODE0_STD_FRT_NUM * CRE_STD_FRT_ELEMENT_SIZE))

/* CONFIG_AURIX_MCMCAN5 */
#define CAN1_NODE1_MRAM_SA (CAN1_NODE0_CRE_STD_TSD_SA + (CONFIG_CAN1_NODE0_STD_TSD_NUM * CRE_STD_TSD_ELEMENT_SIZE))
#define CAN1_NODE1_FLSSA CAN1_NODE1_MRAM_SA
#define CAN1_NODE1_F0SA (CAN1_NODE1_FLSSA + (CONFIG_CAN1_NODE1_SFL_NUM * SID_FILTER_SIZE))
#define CAN1_NODE1_F1SA (CAN1_NODE1_F0SA + (CONFIG_CAN1_NODE1_RF0_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN1_NODE1_RX_BUFSA (CAN1_NODE1_F1SA + (CONFIG_CAN1_NODE1_RF1_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN1_NODE1_EFSA (CAN1_NODE1_RX_BUFSA + (CONFIG_CAN1_NODE1_RXBUF_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN1_NODE1_TX_BUFSA (CAN1_NODE1_EFSA + (CONFIG_CAN1_NODE1_TEF_NUM * TXEVENT_SIZE))
#if defined(MCMCAN5_CRE_ENABLE)
#define CAN1_NODE1_CRE_SA CRE_SA_ALIGN(CAN1_NODE1_TX_BUFSA + ((CONFIG_CAN1_NODE1_DED_TX_BUF_NUM + CONFIG_CAN1_NODE1_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN1_NODE1_CRE_STD_RT_SA (CAN1_NODE1_CRE_SA + CRE_FIXED_SIZE)
#else
#define CAN1_NODE1_CRE_SA CAN1_NODE1_TX_BUFSA + ((CONFIG_CAN1_NODE1_DED_TX_BUF_NUM + CONFIG_CAN1_NODE1_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE))
#define CAN1_NODE1_CRE_STD_RT_SA CAN1_NODE1_CRE_SA
#endif
#define CAN1_NODE1_CRE_STD_FRT_SA (CAN1_NODE1_CRE_STD_RT_SA + (CONFIG_CAN1_NODE1_STD_RT_NUM * CRE_STD_RT_ELEMENT_SIZE))
#define CAN1_NODE1_CRE_STD_TSD_SA (CAN1_NODE1_CRE_STD_FRT_SA + (CONFIG_CAN1_NODE1_STD_FRT_NUM * CRE_STD_FRT_ELEMENT_SIZE))

/* CONFIG_AURIX_MCMCAN6 */
#define CAN1_NODE2_MRAM_SA (CAN1_NODE1_CRE_STD_TSD_SA + (CONFIG_CAN1_NODE1_STD_TSD_NUM * CRE_STD_TSD_ELEMENT_SIZE))
#define CAN1_NODE2_FLSSA CAN1_NODE2_MRAM_SA
#define CAN1_NODE2_F0SA (CAN1_NODE2_FLSSA + (CONFIG_CAN1_NODE2_SFL_NUM * SID_FILTER_SIZE))
#define CAN1_NODE2_F1SA (CAN1_NODE2_F0SA + (CONFIG_CAN1_NODE2_RF0_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN1_NODE2_RX_BUFSA (CAN1_NODE2_F1SA + (CONFIG_CAN1_NODE2_RF1_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN1_NODE2_EFSA (CAN1_NODE2_RX_BUFSA + (CONFIG_CAN1_NODE2_RXBUF_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN1_NODE2_TX_BUFSA (CAN1_NODE2_EFSA + (CONFIG_CAN1_NODE2_TEF_NUM * TXEVENT_SIZE))
#if defined(MCMCAN6_CRE_ENABLE)
#define CAN1_NODE2_CRE_SA CRE_SA_ALIGN(CAN1_NODE2_TX_BUFSA + ((CONFIG_CAN1_NODE2_DED_TX_BUF_NUM + CONFIG_CAN1_NODE2_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN1_NODE2_CRE_STD_RT_SA (CAN1_NODE2_CRE_SA + CRE_FIXED_SIZE)
#else
#define CAN1_NODE2_CRE_SA CAN1_NODE2_TX_BUFSA + ((CONFIG_CAN1_NODE2_DED_TX_BUF_NUM + CONFIG_CAN1_NODE2_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE))
#define CAN1_NODE2_CRE_STD_RT_SA CAN1_NODE2_CRE_SA
#endif
#define CAN1_NODE2_CRE_STD_FRT_SA (CAN1_NODE2_CRE_STD_RT_SA + (CONFIG_CAN1_NODE2_STD_RT_NUM * CRE_STD_RT_ELEMENT_SIZE))
#define CAN1_NODE2_CRE_STD_TSD_SA (CAN1_NODE2_CRE_STD_FRT_SA + (CONFIG_CAN1_NODE2_STD_FRT_NUM * CRE_STD_FRT_ELEMENT_SIZE))

/* CONFIG_AURIX_MCMCAN7 */
#define CAN1_NODE3_MRAM_SA (CAN1_NODE2_CRE_STD_TSD_SA + (CONFIG_CAN1_NODE2_STD_TSD_NUM * CRE_STD_TSD_ELEMENT_SIZE))
#define CAN1_NODE3_FLSSA CAN1_NODE3_MRAM_SA
#define CAN1_NODE3_F0SA (CAN1_NODE3_FLSSA + (CONFIG_CAN1_NODE3_SFL_NUM * SID_FILTER_SIZE))
#define CAN1_NODE3_F1SA (CAN1_NODE3_F0SA + (CONFIG_CAN1_NODE3_RF0_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN1_NODE3_RX_BUFSA (CAN1_NODE3_F1SA + (CONFIG_CAN1_NODE3_RF1_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN1_NODE3_EFSA (CAN1_NODE3_RX_BUFSA + (CONFIG_CAN1_NODE3_RXBUF_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN1_NODE3_TX_BUFSA (CAN1_NODE3_EFSA + (CONFIG_CAN1_NODE3_TEF_NUM * TXEVENT_SIZE))
#if defined(MCMCAN7_CRE_ENABLE)
#define CAN1_NODE3_CRE_SA CRE_SA_ALIGN(CAN1_NODE3_TX_BUFSA + ((CONFIG_CAN1_NODE3_DED_TX_BUF_NUM + CONFIG_CAN1_NODE3_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN1_NODE3_CRE_STD_RT_SA (CAN1_NODE3_CRE_SA + CRE_FIXED_SIZE)
#else
#define CAN1_NODE3_CRE_SA CAN1_NODE3_TX_BUFSA + ((CONFIG_CAN1_NODE3_DED_TX_BUF_NUM + CONFIG_CAN1_NODE3_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE))
#define CAN1_NODE3_CRE_STD_RT_SA CAN1_NODE3_CRE_SA
#endif
#define CAN1_NODE3_CRE_STD_FRT_SA (CAN1_NODE3_CRE_STD_RT_SA + (CONFIG_CAN1_NODE3_STD_RT_NUM * CRE_STD_RT_ELEMENT_SIZE))
#define CAN1_NODE3_CRE_STD_TSD_SA (CAN1_NODE3_CRE_STD_FRT_SA + (CONFIG_CAN1_NODE3_STD_FRT_NUM * CRE_STD_FRT_ELEMENT_SIZE))

/* CAN2 Message RAM Region */

/* CONFIG_AURIX_MCMCAN8 */
#define CAN2_NODE0_MRAM_SA 0x0
#define CAN2_NODE0_FLSSA CAN2_NODE0_MRAM_SA
#define CAN2_NODE0_F0SA (CAN2_NODE0_FLSSA + (CONFIG_CAN2_NODE0_SFL_NUM * SID_FILTER_SIZE))
#define CAN2_NODE0_F1SA (CAN2_NODE0_F0SA + (CONFIG_CAN2_NODE0_RF0_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN2_NODE0_RX_BUFSA (CAN2_NODE0_F1SA + (CONFIG_CAN2_NODE0_RF1_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN2_NODE0_EFSA (CAN2_NODE0_RX_BUFSA + (CONFIG_CAN2_NODE0_RXBUF_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN2_NODE0_TX_BUFSA (CAN2_NODE0_EFSA + (CONFIG_CAN2_NODE0_TEF_NUM * TXEVENT_SIZE))
#if defined(MCMCAN8_CRE_ENABLE)
#define CAN2_NODE0_CRE_SA CRE_SA_ALIGN(CAN2_NODE0_TX_BUFSA + ((CONFIG_CAN2_NODE0_DED_TX_BUF_NUM + CONFIG_CAN2_NODE0_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN2_NODE0_CRE_STD_RT_SA (CAN2_NODE0_CRE_SA + CRE_FIXED_SIZE)
#else
#define CAN2_NODE0_CRE_SA CAN2_NODE0_TX_BUFSA + ((CONFIG_CAN2_NODE0_DED_TX_BUF_NUM + CONFIG_CAN2_NODE0_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE))
#define CAN2_NODE0_CRE_STD_RT_SA CAN2_NODE0_CRE_SA
#endif
#define CAN2_NODE0_CRE_STD_FRT_SA (CAN2_NODE0_CRE_STD_RT_SA + (CONFIG_CAN2_NODE0_STD_RT_NUM * CRE_STD_RT_ELEMENT_SIZE))
#define CAN2_NODE0_CRE_STD_TSD_SA (CAN2_NODE0_CRE_STD_FRT_SA + (CONFIG_CAN2_NODE0_STD_FRT_NUM * CRE_STD_FRT_ELEMENT_SIZE))

/* CONFIG_AURIX_MCMCAN9 */
#define CAN2_N1_MRAM_SA (CAN2_NODE0_CRE_STD_TSD_SA + (CONFIG_CAN2_NODE0_STD_TSD_NUM * CRE_STD_TSD_ELEMENT_SIZE))
#define CAN2_NODE1_FLSSA CAN2_N1_MRAM_SA
#define CAN2_NODE1_F0SA (CAN2_NODE1_FLSSA + (CONFIG_CAN2_NODE1_SFL_NUM * SID_FILTER_SIZE))
#define CAN2_NODE1_F1SA (CAN2_NODE1_F0SA + (CONFIG_CAN2_NODE1_RF0_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN2_NODE1_RX_BUFSA (CAN2_NODE1_F1SA + (CONFIG_CAN2_NODE1_RF1_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN2_NODE1_EFSA (CAN2_NODE1_RX_BUFSA + (CONFIG_CAN2_NODE1_RXBUF_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN2_NODE1_TX_BUFSA (CAN2_NODE1_EFSA + (CONFIG_CAN2_NODE1_TEF_NUM * TXEVENT_SIZE))
#if defined(MCMCAN9_CRE_ENABLE)
#define CAN2_NODE1_CRE_SA CRE_SA_ALIGN(CAN2_NODE1_TX_BUFSA + ((CONFIG_CAN2_NODE1_DED_TX_BUF_NUM + CONFIG_CAN2_NODE1_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN2_NODE1_CRE_STD_RT_SA (CAN2_NODE1_CRE_SA + CRE_FIXED_SIZE)
#else
#define CAN2_NODE1_CRE_SA CAN2_NODE1_TX_BUFSA + ((CONFIG_CAN2_NODE1_DED_TX_BUF_NUM + CONFIG_CAN2_NODE1_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE))
#define CAN2_NODE1_CRE_STD_RT_SA CAN2_NODE1_CRE_SA
#endif
#define CAN2_NODE1_CRE_STD_FRT_SA (CAN2_NODE1_CRE_STD_RT_SA + (CONFIG_CAN2_NODE1_STD_RT_NUM * CRE_STD_RT_ELEMENT_SIZE))
#define CAN2_NODE1_CRE_STD_TSD_SA (CAN2_NODE1_CRE_STD_FRT_SA + (CONFIG_CAN2_NODE1_STD_FRT_NUM * CRE_STD_FRT_ELEMENT_SIZE))

/* CONFIG_AURIX_MCMCAN10 */
#define CAN2_NODE2_MRAM_SA (CAN2_NODE1_CRE_STD_TSD_SA + (CONFIG_CAN2_NODE1_STD_TSD_NUM * CRE_STD_TSD_ELEMENT_SIZE))
#define CAN2_NODE2_FLSSA CAN2_NODE2_MRAM_SA
#define CAN2_NODE2_F0SA (CAN2_NODE2_FLSSA + (CONFIG_CAN2_NODE2_SFL_NUM * SID_FILTER_SIZE))
#define CAN2_NODE2_F1SA (CAN2_NODE2_F0SA + (CONFIG_CAN2_NODE2_RF0_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN2_NODE2_RX_BUFSA (CAN2_NODE2_F1SA + (CONFIG_CAN2_NODE2_RF1_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN2_NODE2_EFSA (CAN2_NODE2_RX_BUFSA + (CONFIG_CAN2_NODE2_RXBUF_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN2_NODE2_TX_BUFSA (CAN2_NODE2_EFSA + (CONFIG_CAN2_NODE2_TEF_NUM * TXEVENT_SIZE))
#if defined(MCMCAN10_CRE_ENABLE)
#define CAN2_NODE2_CRE_SA CRE_SA_ALIGN(CAN2_NODE2_TX_BUFSA + ((CONFIG_CAN2_NODE2_DED_TX_BUF_NUM + CONFIG_CAN2_NODE2_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN2_NODE2_CRE_STD_RT_SA (CAN2_NODE2_CRE_SA + CRE_FIXED_SIZE)
#else
#define CAN2_NODE2_CRE_SA CAN2_NODE2_TX_BUFSA + ((CONFIG_CAN2_NODE2_DED_TX_BUF_NUM + CONFIG_CAN2_NODE2_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE))
#define CAN2_NODE2_CRE_STD_RT_SA CAN2_NODE2_CRE_SA
#endif
#define CAN2_NODE2_CRE_STD_FRT_SA (CAN2_NODE2_CRE_STD_RT_SA + (CONFIG_CAN2_NODE2_STD_RT_NUM * CRE_STD_RT_ELEMENT_SIZE))
#define CAN2_NODE2_CRE_STD_TSD_SA (CAN2_NODE2_CRE_STD_FRT_SA + (CONFIG_CAN2_NODE2_STD_FRT_NUM * CRE_STD_FRT_ELEMENT_SIZE))

/* CONFIG_AURIX_MCMCAN11 */
#define CAN2_NODE3_MRAM_SA (CAN2_NODE2_CRE_STD_TSD_SA + (CONFIG_CAN2_NODE2_STD_TSD_NUM * CRE_STD_TSD_ELEMENT_SIZE))
#define CAN2_NODE3_FLSSA CAN2_NODE3_MRAM_SA
#define CAN2_NODE3_F0SA (CAN2_NODE3_FLSSA + (CONFIG_CAN2_NODE3_SFL_NUM * SID_FILTER_SIZE))
#define CAN2_NODE3_F1SA (CAN2_NODE3_F0SA + (CONFIG_CAN2_NODE3_RF0_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN2_NODE3_RX_BUFSA (CAN2_NODE3_F1SA + (CONFIG_CAN2_NODE3_RF1_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN2_NODE3_EFSA (CAN2_NODE3_RX_BUFSA + (CONFIG_CAN2_NODE3_RXBUF_NUM * (R0_R1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN2_NODE3_TX_BUFSA (CAN2_NODE3_EFSA + (CONFIG_CAN2_NODE3_TEF_NUM * TXEVENT_SIZE))
#if defined(MCMCAN11_CRE_ENABLE)
#define CAN2_NODE3_CRE_SA CRE_SA_ALIGN(CAN2_NODE3_TX_BUFSA + ((CONFIG_CAN2_NODE3_DED_TX_BUF_NUM + CONFIG_CAN2_NODE3_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE)))
#define CAN2_NODE3_CRE_STD_RT_SA (CAN2_NODE3_CRE_SA + CRE_FIXED_SIZE)
#else
#define CAN2_NODE3_CRE_SA CAN2_NODE3_TX_BUFSA + ((CONFIG_CAN2_NODE3_DED_TX_BUF_NUM + CONFIG_CAN2_NODE3_TX_FIFO_Q_NUM) * (T0_T1_SIZE + CANMSG_DATAFILED_SIZE))
#define CAN2_NODE3_CRE_STD_RT_SA CAN2_NODE3_CRE_SA
#endif
#define CAN2_NODE3_CRE_STD_FRT_SA (CAN2_NODE3_CRE_STD_RT_SA + (CONFIG_CAN2_NODE3_STD_RT_NUM * CRE_STD_RT_ELEMENT_SIZE))
#define CAN2_NODE3_CRE_STD_TSD_SA (CAN2_NODE3_CRE_STD_FRT_SA + (CONFIG_CAN2_NODE3_STD_FRT_NUM * CRE_STD_FRT_ELEMENT_SIZE))

#endif /* CONFIG_AURIX_MCMCAN */
#endif /* __VENDOR_CAN_MRAM_TC3_H */
