/****************************************************************************
 *  Copyright (C) 2025 Xiaomi Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ***************************************************************************/

#ifndef __CAN_FILTER_H__
#define __CAN_FILTER_H__

#include "Can/Can/IfxCan_Can.h"
#include "Can/Std/IfxCan.h"
#include "aurix_mcmcan.h"

#define CONFIG_CAN0_NODE0_SFL_NUM ((CONFIG_CAN0_NODE0_RXBUF_NUM) + (CONFIG_CAN0_NODE0_RF_NUM))
#define CONFIG_CAN0_NODE0_RF0_NUM 2
#define CONFIG_CAN0_NODE0_RF1_NUM 27
#define CONFIG_CAN0_NODE0_RF_NUM ((CONFIG_CAN0_NODE0_RF0_NUM) + (CONFIG_CAN0_NODE0_RF1_NUM))
#define CONFIG_CAN0_NODE0_RXBUF_NUM 0
#define CONFIG_CAN0_NODE1_SFL_NUM ((CONFIG_CAN0_NODE1_RXBUF_NUM) + (CONFIG_CAN0_NODE1_RF_NUM))
#define CONFIG_CAN0_NODE1_RF0_NUM 0
#define CONFIG_CAN0_NODE1_RF1_NUM 0
#define CONFIG_CAN0_NODE1_RF_NUM ((CONFIG_CAN0_NODE1_RF0_NUM) + (CONFIG_CAN0_NODE1_RF1_NUM))
#define CONFIG_CAN0_NODE1_RXBUF_NUM 0
#define CONFIG_CAN0_NODE2_SFL_NUM ((CONFIG_CAN0_NODE2_RXBUF_NUM) + (CONFIG_CAN0_NODE2_RF_NUM))
#define CONFIG_CAN0_NODE2_RF0_NUM 1
#define CONFIG_CAN0_NODE2_RF1_NUM 12
#define CONFIG_CAN0_NODE2_RF_NUM ((CONFIG_CAN0_NODE2_RF0_NUM) + (CONFIG_CAN0_NODE2_RF1_NUM))
#define CONFIG_CAN0_NODE2_RXBUF_NUM 0
#define CONFIG_CAN0_NODE3_SFL_NUM ((CONFIG_CAN0_NODE3_RXBUF_NUM) + (CONFIG_CAN0_NODE3_RF_NUM))
#define CONFIG_CAN0_NODE3_RF0_NUM 0
#define CONFIG_CAN0_NODE3_RF1_NUM 0
#define CONFIG_CAN0_NODE3_RF_NUM ((CONFIG_CAN0_NODE3_RF0_NUM) + (CONFIG_CAN0_NODE3_RF1_NUM))
#define CONFIG_CAN0_NODE3_RXBUF_NUM 0
#define CONFIG_CAN1_NODE0_SFL_NUM ((CONFIG_CAN1_NODE0_RXBUF_NUM) + (CONFIG_CAN1_NODE0_RF_NUM))
#define CONFIG_CAN1_NODE0_RF0_NUM 0
#define CONFIG_CAN1_NODE0_RF1_NUM 2
#define CONFIG_CAN1_NODE0_RF_NUM ((CONFIG_CAN1_NODE0_RF0_NUM) + (CONFIG_CAN1_NODE0_RF1_NUM))
#define CONFIG_CAN1_NODE0_RXBUF_NUM 0
#define CONFIG_CAN1_NODE1_SFL_NUM ((CONFIG_CAN1_NODE1_RXBUF_NUM) + (CONFIG_CAN1_NODE1_RF_NUM))
#define CONFIG_CAN1_NODE1_RF0_NUM 0
#define CONFIG_CAN1_NODE1_RF1_NUM 0
#define CONFIG_CAN1_NODE1_RF_NUM ((CONFIG_CAN1_NODE1_RF0_NUM) + (CONFIG_CAN1_NODE1_RF1_NUM))
#define CONFIG_CAN1_NODE1_RXBUF_NUM 0
#define CONFIG_CAN1_NODE2_SFL_NUM ((CONFIG_CAN1_NODE2_RXBUF_NUM) + (CONFIG_CAN1_NODE2_RF_NUM))
#define CONFIG_CAN1_NODE2_RF0_NUM 0
#define CONFIG_CAN1_NODE2_RF1_NUM 3
#define CONFIG_CAN1_NODE2_RF_NUM ((CONFIG_CAN1_NODE2_RF0_NUM) + (CONFIG_CAN1_NODE2_RF1_NUM))
#define CONFIG_CAN1_NODE2_RXBUF_NUM 0
#define CONFIG_CAN1_NODE3_SFL_NUM ((CONFIG_CAN1_NODE3_RXBUF_NUM) + (CONFIG_CAN1_NODE3_RF_NUM))
#define CONFIG_CAN1_NODE3_RF0_NUM 0
#define CONFIG_CAN1_NODE3_RF1_NUM 0
#define CONFIG_CAN1_NODE3_RF_NUM ((CONFIG_CAN1_NODE3_RF0_NUM) + (CONFIG_CAN1_NODE3_RF1_NUM))
#define CONFIG_CAN1_NODE3_RXBUF_NUM 0
#define CONFIG_CAN2_NODE0_SFL_NUM ((CONFIG_CAN2_NODE0_RXBUF_NUM) + (CONFIG_CAN2_NODE0_RF_NUM))
#define CONFIG_CAN2_NODE0_RF0_NUM 0
#define CONFIG_CAN2_NODE0_RF1_NUM 0
#define CONFIG_CAN2_NODE0_RF_NUM ((CONFIG_CAN2_NODE0_RF0_NUM) + (CONFIG_CAN2_NODE0_RF1_NUM))
#define CONFIG_CAN2_NODE0_RXBUF_NUM 0
#define CONFIG_CAN2_NODE1_SFL_NUM ((CONFIG_CAN2_NODE1_RXBUF_NUM) + (CONFIG_CAN2_NODE1_RF_NUM))
#define CONFIG_CAN2_NODE1_RF0_NUM 0
#define CONFIG_CAN2_NODE1_RF1_NUM 0
#define CONFIG_CAN2_NODE1_RF_NUM ((CONFIG_CAN2_NODE1_RF0_NUM) + (CONFIG_CAN2_NODE1_RF1_NUM))
#define CONFIG_CAN2_NODE1_RXBUF_NUM 0
#define CONFIG_CAN2_NODE2_SFL_NUM ((CONFIG_CAN2_NODE2_RXBUF_NUM) + (CONFIG_CAN2_NODE2_RF_NUM))
#define CONFIG_CAN2_NODE2_RF0_NUM 0
#define CONFIG_CAN2_NODE2_RF1_NUM 0
#define CONFIG_CAN2_NODE2_RF_NUM ((CONFIG_CAN2_NODE2_RF0_NUM) + (CONFIG_CAN2_NODE2_RF1_NUM))
#define CONFIG_CAN2_NODE2_RXBUF_NUM 0
#define CONFIG_CAN2_NODE3_SFL_NUM ((CONFIG_CAN2_NODE3_RXBUF_NUM) + (CONFIG_CAN2_NODE3_RF_NUM))
#define CONFIG_CAN2_NODE3_RF0_NUM 0
#define CONFIG_CAN2_NODE3_RF1_NUM 0
#define CONFIG_CAN2_NODE3_RF_NUM ((CONFIG_CAN2_NODE3_RF0_NUM) + (CONFIG_CAN2_NODE3_RF1_NUM))
#define CONFIG_CAN2_NODE3_RXBUF_NUM 0
#define CONFIG_CAN3_NODE0_SFL_NUM ((CONFIG_CAN3_NODE0_RXBUF_NUM) + (CONFIG_CAN3_NODE0_RF_NUM))
#define CONFIG_CAN3_NODE0_RF0_NUM 0
#define CONFIG_CAN3_NODE0_RF1_NUM 0
#define CONFIG_CAN3_NODE0_RF_NUM ((CONFIG_CAN3_NODE0_RF0_NUM) + (CONFIG_CAN3_NODE0_RF1_NUM))
#define CONFIG_CAN3_NODE0_RXBUF_NUM 0
#define CONFIG_CAN3_NODE1_SFL_NUM ((CONFIG_CAN3_NODE1_RXBUF_NUM) + (CONFIG_CAN3_NODE1_RF_NUM))
#define CONFIG_CAN3_NODE1_RF0_NUM 0
#define CONFIG_CAN3_NODE1_RF1_NUM 0
#define CONFIG_CAN3_NODE1_RF_NUM ((CONFIG_CAN3_NODE1_RF0_NUM) + (CONFIG_CAN3_NODE1_RF1_NUM))
#define CONFIG_CAN3_NODE1_RXBUF_NUM 0
#define CONFIG_CAN3_NODE2_SFL_NUM ((CONFIG_CAN3_NODE2_RXBUF_NUM) + (CONFIG_CAN3_NODE2_RF_NUM))
#define CONFIG_CAN3_NODE2_RF0_NUM 0
#define CONFIG_CAN3_NODE2_RF1_NUM 0
#define CONFIG_CAN3_NODE2_RF_NUM ((CONFIG_CAN3_NODE2_RF0_NUM) + (CONFIG_CAN3_NODE2_RF1_NUM))
#define CONFIG_CAN3_NODE2_RXBUF_NUM 0
#define CONFIG_CAN3_NODE3_SFL_NUM ((CONFIG_CAN3_NODE3_RXBUF_NUM) + (CONFIG_CAN3_NODE3_RF_NUM))
#define CONFIG_CAN3_NODE3_RF0_NUM 0
#define CONFIG_CAN3_NODE3_RF1_NUM 0
#define CONFIG_CAN3_NODE3_RF_NUM ((CONFIG_CAN3_NODE3_RF0_NUM) + (CONFIG_CAN3_NODE3_RF1_NUM))
#define CONFIG_CAN3_NODE3_RXBUF_NUM 0
#define CONFIG_CAN4_NODE0_SFL_NUM ((CONFIG_CAN4_NODE0_RXBUF_NUM) + (CONFIG_CAN4_NODE0_RF_NUM))
#define CONFIG_CAN4_NODE0_RF0_NUM 0
#define CONFIG_CAN4_NODE0_RF1_NUM 0
#define CONFIG_CAN4_NODE0_RF_NUM ((CONFIG_CAN4_NODE0_RF0_NUM) + (CONFIG_CAN4_NODE0_RF1_NUM))
#define CONFIG_CAN4_NODE0_RXBUF_NUM 0
#define CONFIG_CAN4_NODE1_SFL_NUM ((CONFIG_CAN4_NODE1_RXBUF_NUM) + (CONFIG_CAN4_NODE1_RF_NUM))
#define CONFIG_CAN4_NODE1_RF0_NUM 0
#define CONFIG_CAN4_NODE1_RF1_NUM 0
#define CONFIG_CAN4_NODE1_RF_NUM ((CONFIG_CAN4_NODE1_RF0_NUM) + (CONFIG_CAN4_NODE1_RF1_NUM))
#define CONFIG_CAN4_NODE1_RXBUF_NUM 0
#define CONFIG_CAN4_NODE2_SFL_NUM ((CONFIG_CAN4_NODE2_RXBUF_NUM) + (CONFIG_CAN4_NODE2_RF_NUM))
#define CONFIG_CAN4_NODE2_RF0_NUM 0
#define CONFIG_CAN4_NODE2_RF1_NUM 0
#define CONFIG_CAN4_NODE2_RF_NUM ((CONFIG_CAN4_NODE2_RF0_NUM) + (CONFIG_CAN4_NODE2_RF1_NUM))
#define CONFIG_CAN4_NODE2_RXBUF_NUM 0
#define CONFIG_CAN4_NODE3_SFL_NUM ((CONFIG_CAN4_NODE3_RXBUF_NUM) + (CONFIG_CAN4_NODE3_RF_NUM))
#define CONFIG_CAN4_NODE3_RF0_NUM 0
#define CONFIG_CAN4_NODE3_RF1_NUM 0
#define CONFIG_CAN4_NODE3_RF_NUM ((CONFIG_CAN4_NODE3_RF0_NUM) + (CONFIG_CAN4_NODE3_RF1_NUM))
#define CONFIG_CAN4_NODE3_RXBUF_NUM 0



#define CAN0_NODE0_RXBUF_FILT can0_node0_std_rxbuf_filter
#define CAN0_NODE0_RF0_FILT can0_node0_std_rxfifo0_filter
#define CAN0_NODE0_RF1_FILT can0_node0_std_rxfifo1_filter
#define CAN1_NODE0_RXBUF_FILT can1_node0_std_rxbuf_filter
#define CAN1_NODE0_RF0_FILT can1_node0_std_rxfifo0_filter
#define CAN1_NODE0_RF1_FILT can1_node0_std_rxfifo1_filter
#define CAN0_NODE2_RXBUF_FILT can0_node2_std_rxbuf_filter
#define CAN0_NODE2_RF0_FILT can0_node2_std_rxfifo0_filter
#define CAN0_NODE2_RF1_FILT can0_node2_std_rxfifo1_filter
#define CAN1_NODE2_RXBUF_FILT can1_node2_std_rxbuf_filter
#define CAN1_NODE2_RF0_FILT can1_node2_std_rxfifo0_filter
#define CAN1_NODE2_RF1_FILT can1_node2_std_rxfifo1_filter


extern const canid_t can0_node0_std_rxbuf_filter[CONFIG_CAN0_NODE0_RXBUF_NUM];
extern const can_std_filter can0_node0_std_rxfifo0_filter[CONFIG_CAN0_NODE0_RF0_NUM];
extern const can_std_filter can0_node0_std_rxfifo1_filter[CONFIG_CAN0_NODE0_RF1_NUM];
extern const canid_t can1_node0_std_rxbuf_filter[CONFIG_CAN1_NODE0_RXBUF_NUM];
extern const can_std_filter can1_node0_std_rxfifo0_filter[CONFIG_CAN1_NODE0_RF0_NUM];
extern const can_std_filter can1_node0_std_rxfifo1_filter[CONFIG_CAN1_NODE0_RF1_NUM];
extern const canid_t can0_node2_std_rxbuf_filter[CONFIG_CAN0_NODE2_RXBUF_NUM];
extern const can_std_filter can0_node2_std_rxfifo0_filter[CONFIG_CAN0_NODE2_RF0_NUM];
extern const can_std_filter can0_node2_std_rxfifo1_filter[CONFIG_CAN0_NODE2_RF1_NUM];
extern const canid_t can1_node2_std_rxbuf_filter[CONFIG_CAN1_NODE2_RXBUF_NUM];
extern const can_std_filter can1_node2_std_rxfifo0_filter[CONFIG_CAN1_NODE2_RF0_NUM];
extern const can_std_filter can1_node2_std_rxfifo1_filter[CONFIG_CAN1_NODE2_RF1_NUM];

#endif /* __CAN_FILTER_H__ */